// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicPlayerSyncServer.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MusicPlayerSyncServer.Migrations
{
    [DbContext(typeof(SongDbContext))]
    partial class SongDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MusicPlayerSyncInterface.DTOs.SongHistoryEntry", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<Guid?>("SongId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("ScoreChange")
                        .HasColumnType("real");

                    // Server-only shadow property: the cursor of the incremental history pull
                    // (see SongHistorySequencer and the server SongDbContext).
                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "SongId", "Date");

                    b.HasIndex("SongId");

                    b.HasIndex("UserId", "Sequence");

                    b.ToTable("SongHistoryEntries");
                });

            modelBuilder.Entity("MusicPlayerSyncInterface.DTOs.SongLibraryMigration", b =>
                {
                    b.Property<Guid>("MigrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MigrationNumber")
                        .HasColumnType("integer");

                    b.Property<string>("MigrationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NewName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OldName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SongId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MigrationId");

                    b.HasIndex("UserId", "MigrationNumber")
                        .IsUnique();

                    b.ToTable("SongLibraryMigrations");
                });

            modelBuilder.Entity("MusicPlayerSyncInterface.DTOs.UpvotedSong", b =>
                {
                    b.Property<Guid>("SongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Score")
                        .HasColumnType("real");

                    b.Property<int>("Streak")
                        .HasColumnType("integer");

                    b.Property<int>("TotalDislikes")
                        .HasColumnType("integer");

                    b.Property<int>("TotalLikes")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Volume")
                        .HasColumnType("real");

                    b.HasKey("SongId");

                    b.HasIndex("UserId", "Name", "Artist", "Album")
                        .IsUnique();

                    b.ToTable("UpvotedSongs");
                });

            modelBuilder.Entity("MusicPlayerSyncInterface.DTOs.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("UserDisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserHandle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MusicPlayerSyncInterface.DTOs.SongHistoryEntry", b =>
                {
                    b.HasOne("MusicPlayerSyncInterface.DTOs.UpvotedSong", "UpvotedSong")
                        .WithMany()
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UpvotedSong");
                });

            modelBuilder.Entity("MusicPlayerSyncInterface.DTOs.SongLibraryMigration", b =>
                {
                    b.HasOne("MusicPlayerSyncInterface.DTOs.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("MusicPlayerSyncInterface.DTOs.UpvotedSong", b =>
                {
                    b.HasOne("MusicPlayerSyncInterface.DTOs.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
